# Generated by Django 5.2.4 on 2025-07-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="search",
            old_name="created_at",
            new_name="searched_at",
        ),
        migrations.RemoveField(
            model_name="search",
            name="keyword",
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="source_name",
            field=models.CharField(default="Unknown Source", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="url_to_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="query",
            field=models.CharField(default="Default Query", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="search.search",
            ),
        ),
    ]
